general {
  uid = "owntone"
  logfile = "/dev/stdout"
  loglevel = log
  trusted_networks = { "localhost" }
  ipv6 = no
  cache_dir = "/var/cache/owntone"
  speaker_autoselect = no
  start_buffer_ms = 1000
}

library {
  name = "Ring HomePod Doorbell"
  port = 3689
  directories = { "/srv/media" }
}

audio {
  nickname = "Disabled"
  type = "disabled"
}

mpd {
  port = 0
}
